config/routes.rb
Poll::Application.routes.draw do
  get "votes/create"

  resources :epolls
  resources :votes

  resources :authentications

  devise_for :users, :path => '', path_names: {sign_in: "login", sign_out: "logout"},
  controllers: {omniauth_callbacks: "authentications", registrations: "registrations"}
  match 'mypolls' => 'epolls#mypolls'
  get "homefront/index"
   get "homefront/about"
  match 'statistics/:id' => 'epolls#statistics', :as => 'statistics'
match 'users/auth/:provider/callback' => 'authentications#create'
match '/auth/:provider/callback' => 'authentications#create'
match 'trending' => 'epolls#trending'
match 'policy' => 'homefront#policy'
match 'the-big-idea' => 'homefront#idea', :as => 'idea'
match 'about' => 'homefront#about'

  root :to => 'homefront#index'

end

app/models/epoll.rb
class Epoll < ActiveRecord::Base
  extend FriendlyId
  friendly_id :question, use: :slugged
  auto_strip_attributes :question, :squish => true, :nullify => false
  attr_accessible :question, :status, :timeout, :user_id, :options_attributes
  has_many :options, :dependent => :destroy
  belongs_to :user
  accepts_nested_attributes_for :options, :allow_destroy => true
  validates_presence_of :question
  validates_uniqueness_of :question
  validates_associated :options
  validates_presence_of :options
  before_validation :require_two_options

    private
      def require_two_options
        errors.add(:base, "You must provide at least two options") if options.size < 2
      end
      
end

app/controllers/epolls_controller.rb
class EpollsController < ApplicationController
  # GET /epolls
  # GET /epolls.json
  before_filter :authenticate_user!, :except => [:show, :index, :trending]
  def index
    @epolls = Epoll.paginate(:include => [:options , { :options => :votes }], :page => params[:page], :per_page => 6).order("created_at DESC")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @epolls }
    end
  end
  
  def mypolls
    @epolls = current_user.epolls.paginate(:include => [:options , { :options => :votes }], :page => params[:page], :per_page => 6).order("created_at DESC")
     respond_to do |format|
        format.html # mypolls.html.erb
        format.json { render json: @epolls }
    end
  end
  
  def trending
    @epolls = Epoll.joins(:options).group("epolls.id").paginate(:page => params[:page], :per_page => 6 , :total_entries => 18).order("sum(votes_count) DESC")
     respond_to do |format|
        format.html # mypolls.html.erb
        format.json { render json: @epolls }
    end
  end
  
  def statistics
    if Epoll.find(params[:id], :include => { :options => :votes }).user_id.to_i == current_user.id
    @epoll = Epoll.find(params[:id])
    @whichuser = User.find(@epoll.user_id).authentications.first.user_name if User.find(@epoll.user_id).authentications.exists?
  else
   raise ActiveRecord::RecordNotFound
  end
  
  end
  

  # GET /epolls/1
  # GET /epolls/1.json
  def show
    @epoll = Epoll.find(params[:id], :include => { :options => :votes })
    @whichuser = User.find(@epoll.user_id).authentications.first.user_name if User.find(@epoll.user_id).authentications.exists?
    @vote = Vote.new
    @vote.option_id = whichvote 
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @epoll }
    end
  end

  # GET /epolls/new
  # GET /epolls/new.json
  def new
    @epoll = Epoll.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @epoll }
    end
  end

  # GET /epolls/1/edit
  def edit
    
    unless Epoll.find(params[:id]).user_id.to_i == current_user.id
        redirect_to request.referer
      end
      
      @epoll = Epoll.find(params[:id])
    
  end

  # POST /epolls
  # POST /epolls.json
  def create
    @epoll = Epoll.new(params[:epoll])

    @epoll.user_id = current_user.id
    respond_to do |format|
      if @epoll.save
        format.html { redirect_to @epoll, notice: 'Poll was successfully created.' }
        format.json { render json: @epoll, status: :created, location: @epoll }
      else
        format.html { render action: "new" }
        format.json { render json: @epoll.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /epolls/1
  # PUT /epolls/1.json
  def update
    @epoll = Epoll.find(params[:id])

    respond_to do |format|
      if @epoll.update_attributes(params[:epoll])
        format.html { redirect_to @epoll, notice: 'Poll was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @epoll.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /epolls/1
  # DELETE /epolls/1.json
  def destroy
    
if Epoll.find(params[:id]).user_id.to_i == current_user.id

        
    @epoll = Epoll.find(params[:id])
    @epoll.destroy

    respond_to do |format|
      format.html { redirect_to epolls_url }
      format.json { head :no_content }
    end
  else
    redirect_to request.referer
  end
end
end

app/helpers/epolls_helper.rb
module EpollsHelper
end

app/views/epolls/_form.html.erb
<%= javascript_include_tag 'http://sizr.net/scripts/datepicker.js' %>
<%= stylesheet_link_tag "http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css", "application" %>

<%= nested_form_for(@epoll) do |f| %>
  <% if @epoll.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@epoll.errors.count, "error") %> prohibited this poll from being saved:</h2>

      <ul>
      <% @epoll.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


<div class="notice"><%= notice %></div>
<div class="alert"><%= alert%></div>

<div class="empoll-new">
	<br/>
  <div class="field">
	
    <div class="center-text"><h2>Question<br /></h2></div>
    <div class="long-text"><%= f.text_field :question %></div>
  </div>
  <div class="field">
    <div class="center-text"><h2>When should this Poll end?<br /></h2></div>
    <div class="center-div span10"><%= f.text_field :timeout , :id =>'d_picker' %></div>
  </div>
</div>
<div class="empoll-new">
 <div class="center-text"><h2>Options for this Poll</h2></div>
<div class="center-div span20"><div class="center-text">
<%= f.fields_for :options do |op| %>
  <%= op.text_field :name %>
  <%= op.link_to_remove "&#10006; Remove".html_safe, :class => "remove_option" %>
<% end %>


<p><%= f.link_to_add "&#10010; &nbsp; Add option".html_safe, :options, :class => "add_option" %></p>
</div>
</div></div>
<%= f.submit 'Create Poll', :class => 'sub_button' %>
  <div class="actions">
    
<div class="min-text notice center-text"></div>
  

<% end %>

<script>
$(document).ready(function() {
	
	 $('#d_picker').datetimepicker({dateFormat: 'yy-mm-dd'});
	
$('form').on('nested:fieldRemoved', function(event) {
  	var numOfVisibleRows = $('.fields').filter(function() {
	  return $(this).css('display') !== 'none';
	}).length;
	if (numOfVisibleRows < 2 )
	{
		 $('.min-text').text("Note: You must have atleast 2 options to save this poll.");
		 $('.actions input').attr("disabled", true);
		$('.sub_button').css("display", "none")
	}
	else
	{
		 $('.actions input').attr("disabled", false);
		$('.min-text').text("");
	}
})

$('form').on('nested:fieldAdded', function(event) {
  	var numOfVisibleRows = $('.fields').filter(function() {
	  return $(this).css('display') !== 'none';
	}).length;
	if (numOfVisibleRows < 2 )
	{
		 $('.min-text').text("Note: You must have atleast 2 options to save this poll.");
		 $('.actions input').attr("disabled", true);
		$('.sub_button').css("display", "none")
	}
	else
	{
		
		 $('.actions input').attr("disabled", false);
		$('.min-text').text("");
		$('.sub_button').css("display", "block")
	}
})
});
</script>

app/views/epolls/_listpolls.html.erb
<div class="center-text"><%= will_paginate @epolls %></div>

<% @epolls.each do |epoll| %>
 
	<div class="empoll-new">
		<div class="question_side">
    <div class="greenheader"><%=link_to epoll.question, epoll_path(epoll) %> <br/></div>
	<span class="lightgrey">Created by @<%= find_user_from_epoll(epoll) %> on <%= epoll.created_at.to_date.to_formatted_s(:long_ordinal) %> <br/><br/>
		<div class="polls_image"> <%=pluralize(epoll.options.flat_map(&:votes).count, 'vote')%> cast.</div>
		</td></span>
    </div>
<div class="edit_side">
<%if user_signed_in? && current_user.id == epoll.user_id%>
    <td><%= link_to 'Edit', edit_epoll_path(epoll), :class=> "icon_edit" %></td>
    <td><%= link_to 'Destroy', epoll, method: :delete, data: { confirm: 'Are you sure?' } , :class=> "icon_destroy"%></td>
<%end%>
</div>
</div>

<% end %>
<div class="center-text"><%= will_paginate @epolls %></div>


<br />

app/views/epolls/edit.html.erb
<h1>Editing epoll</h1>

<%= render 'form' %>
<div class="center-text">
<%= link_to 'Show', @epoll %> |
<%= link_to 'Back', epolls_path %>
</div>

app/views/epolls/index.html.erb
<div class="center-text"><h1>Polled Timeline</h1></div>


<%= render 'listpolls' %>

app/views/epolls/mypolls.html.erb
<div class="center-text"><h1>My Polls</h1></div>

<%= render 'listpolls' %>
<div class="center-text lightgrey">You've created <%=count_poll%> poll(s) so far.</div>

app/views/epolls/new.html.erb
<div class="center-text"><h1>Create a new poll</h1></div>

<%= render 'form' %>

<div class="center-text"><%= link_to 'Back', epolls_path %></div>

app/views/epolls/show.html.erb
<br/><div class="center-text"><p id="notice"><%= notice %></p></div>



<br/> <br/> <div class="poll_icon"><%= @epoll.question %></div>

<div class="indent_little">
  Poll by @<%= @whichuser %> on <%=@epoll.created_at.to_date.to_formatted_s(:long_ordinal)%>.
</div>


<div class="form_row">
	<br/><br/><br/>


<%= semantic_form_for @vote do |f| %>
  <%= f.inputs do%>
   <%= f.input :option_id, :as => :radio , :input_html => {:class => 'icheck-me'},  :collection => @epoll.options.order("votes_count DESC"), member_label: Proc.new {|a| "<div class='custom_radio'>#{a.name}</div><br/><div class='bar_holder'><div class='bar_inner'><div class='progbar_value'>#{show_vote_parts(a)}</div></div><div class='fr'>#{pluralize(a.votes_count, 'vote')} </div></div>".html_safe},  :label =>""%>
<%end%>

<%unless vote_has_been_cast?%>
 <%= f.actions do %>
      <%= f.action :submit, :button_html => { :class => "sub_button" } , :label => "Submit Vote"%>
    <% end %>
<%else%>
<div class="center-text already-cast">
You've already cast your vote </div>
<%end%>

<% end %>

</div>

<br/>
<div class="center-text">
	<p class="ordinal">
  This poll ends on <%= @epoll.timeout.to_date.to_formatted_s(:long_ordinal) %>.




<%if user_signed_in?%>
<%if current_user.id == @epoll.user_id %> <%= link_to 'Edit', edit_epoll_path(@epoll) %> | <%= link_to 'Statistics', statistics_path(@epoll) %><%end%> |<%end%>
<%= link_to 'Back to all polls', epolls_path %></p></div>

app/views/epolls/statistics.html.erb
<div class="center-text"><h2> Statistics for Poll: "<%=@epoll.question %>"</h2></div>
<div class="empoll-new">
<p class="stattext">
	<br/>
	Total options:
	<%=@epoll.options.count%> <br/>
	Total votes cast:
	<%=@epoll.options.sum(:votes_count)%>
	<br/>
	Top country:
	<%=@epoll.options.flat_map(&:votes).flat_map(&:location).max%>
	<br/>
Top City: 
	<%=@epoll.options.flat_map(&:votes).flat_map(&:city).max%>
	<br/>
Top Platform: 
	<%=@epoll.options.flat_map(&:votes).flat_map(&:os).max%>
<br/>

Top Browser: 
<%=@epoll.options.flat_map(&:votes).flat_map(&:browser).max%></p>
<h2> Option breakdown </h2>

<%@epoll.options.each do |option|%>
<p class="statheader">Option Name: <%=option.name%></p>
<p class="stattext">
Votes Cast: <%=@temp_cnt = option.votes_count%> <br/>
Top Country: <%=option.votes.flat_map(&:location).max || "Not enough votes on this option to determine this."%><br/>
Top City: <%=option.votes.flat_map(&:city).max || "Not enough votes on this option to determine this."%><br/>
Top Platform: <%=(option.votes.flat_map(&:os).max || "Not enough votes on this option to determine this.").capitalize%><br/>
Top Browser: <%=option.votes.flat_map(&:browser).max || "Not enough votes on this option to determine this."%><br/>
<%@count =0 %>
Percentage mobile users: <%option.votes.flat_map(&:is_mobile).each {|n| @count+= 1 if n}|| "Not enough votes on this option to determine this."%><%= @temp_cnt==0?"No Statistics":"#{(@count/@temp_cnt)*100}%"  %><br/></p>
<%end%>
<br/>
</div>

app/views/epolls/trending.html.erb
<div class="center-text"><h1>Trending Polls</h1></div>


<%= render 'listpolls' %>