config/routes.rb
Poll::Application.routes.draw do
  get "votes/create"

  resources :epolls
  resources :votes

  resources :authentications

  devise_for :users, :path => '', path_names: {sign_in: "login", sign_out: "logout"},
  controllers: {omniauth_callbacks: "authentications", registrations: "registrations"}
  match 'mypolls' => 'epolls#mypolls'
  get "homefront/index"
   get "homefront/about"
  match 'statistics/:id' => 'epolls#statistics', :as => 'statistics'
match 'users/auth/:provider/callback' => 'authentications#create'
match '/auth/:provider/callback' => 'authentications#create'
match 'trending' => 'epolls#trending'
match 'policy' => 'homefront#policy'
match 'the-big-idea' => 'homefront#idea', :as => 'idea'
match 'about' => 'homefront#about'

  root :to => 'homefront#index'

end

app/controllers/homefront_controller.rb
class HomefrontController < ApplicationController
  def index
  end
  def policy
  end
  def idea
  end
  def about
  end
end

app/helpers/homefront_helper.rb
module HomefrontHelper
end

app/views/homefront/about.html.erb
	<h1 class="center-text">About</h1><div class="big-idea">

<h2>What is Pollled?</h2> 
<p class="bigtext2">
Pollled is an exciting and developing social innovation project by Sizr Studios. It is the ultimate polling solution packed with statistics, data and reports! It is developed on Ruby on Rails 3.2 and has been tested by beta testers over a period of one month. With developers at Sizr being a part of the very few on the PRO Rails Community in India, huge amount of time has been spent on the optimization and security of data. Pollled uses a single shot, custom solution based on OmniAuth/Devise for authentication. Pollled is OS and Device independent. It is simple and flexible.<br/><br/><br/>


<h2>How much does it cost?</h2>
<p class="bigtext2">
Pollled is a free web service with no hidden fees or long-term commitments. However, with further development and addition of premium features Sizr Studios holds all rights to convert Pollled into a freemium service.
</p>
<br/><br/>
<h2>How to use?</h2>
<p class="bigtext2">
If you find our extremely simple UI a little challenging, please find our tutorial here.</p>
<br/><br/>
<h2>The big Idea?</h2>
<p class="bigtext2">
Developers at Sizr are constantly working on improving and adding  features to Pollled. Pollled hopes to replace expensive audience response hardware with cutting edge web technology. It aims to grow into the easiest way to gather live responses at conferences, presentations, classrooms etc. or even for market research using the power of the internet.<br/><br/>

With Twitter based authentication Pollled can eventually be used for/to:<br/><br/>
•	Audience choice awards<br/><br/>
•	Replace expensive clickers<br/><br/>
•	Surveys	<br/><br/>
•	Brainstorming <br/><br/>
•	Market research <br/><br/>
•	Training comprehension checks <br/><br/>	
•	Grading in-class quizzes <br/><br/>	
•	Political elections <br/><br/></p>
<br/><br/>

This document was last updated on July 3, 2013<br/><br/><br/></p></div>

app/views/homefront/idea.html.erb
<h1 class="center-text">What's the Big idea?</h1>
<div class = "big-idea">
	
		<div class="center-text"><p class="bigtext1">There is one thing stronger than all the armies in the world, and that is an idea whose time has come.<br/> <i>~Victor Hugo</i></p></div>
		<p class="bigtext2"><br/><br/><br/>
		It's 2013 and the world is running out of ideas. In the world of rapid scaling web services, ideas come by at the speed of sound and are dropped even faster. We feel that any idea, even a bad one, is worth consideration. Hence on account of the release of this Beta, we're opening a no holds barred 'idea gathering competition' (We didn't know what else to call it, really). We're looking for an idea for a web service, that can scale to match the user base of something like Facebook or Twitter. <i>We can build it</i>, all we need is a idea to work on. <br/><br/> 
		The first thing that probably comes to your mind is - "Can't you think of something on your own?" or "What's in it for me?". To answer both questions: We've thought. We've thought hard and some of the ideas that we felt were "awesome" have already been put into motion. But me and my team are of the belief that every individual has ideas worth giving an audience to. We don't want that brain cell of yours holding the idea to simply wither away because you never found someone to put it in motion.<br/> <br/>  As for the second question - "What's in it for you", we're giving away <strong>1%</strong> of all profits we make of your idea for life. If it scales, and reaches the heights that something like Facebook has reached, then your wallet will be a few million dollars heavier and you'll be thanking that one brain cell for it's rendered service. <br/><br/> 
		But again, there's two sides to the story - Your biz idea may simply fall flat. But let us take the risk, after all - It's just an idea you spent. If you feel you like where we're headed, you could even join our marketing department while you're at it. <br/><br/> 
		So without much further ado, send your ideas to:<br/>
		<strong>mayya@sizr.net</strong><br/>
		<br/>

		Meanwhile, we'll be bringing new web services that are doing the rounds in more developed nations and testing them on Indian waters.
		
		
		
		<br/><br/>
		May the best idea win.<br/>
		<br/>
		<strong>Varun Mayya<br/>
		Senior Partner & Lead Developer, Sizr Studios<br/></strong>
	</p>
</div>

app/views/homefront/index.html.erb
<div class="center-text"><br/><br/><br/><h1>Welcome to Pollled.</h1>
<h2>The ultimate <span class="nbcolor">FREE</span> polling solution for the Twitterverse and beyond, packed with statistics, data and reports! <br/>
	</h2>
<br/><br/><br/><br/><br/>
<p class="graytext" style="text-decoration:none !important;">New User?  <%= link_to "Find out more.", homefront_about_path %></p>
<br/><br/><br/><br/><br/><br/><br/>
<h4> Latest Polls </h4>
 <div class="linklist">
<%Epoll.order("created_at DESC").first(3).each do |epoll|%>
<%=link_to epoll.question, epoll_path(epoll)%><br/>
<%end%></div>
</div>

app/views/homefront/policy.html.erb
	<h1 class="center-text">Privacy Policy</h1><div class="big-idea">
<p class="bigtext2">This Privacy Policy governs the manner in which Pollled collects, uses, maintains and discloses information collected from users (each, a "User") of Pollled. <br/><br/><br/></p>

<h2>Personal identification information</h2> 
<p class="bigtext2">
We may collect personal identification information from Users in a variety of ways, including, but not limited to, when Users visit our site, register on the site, respond to a poll, fill out a form, and in connection with other activities, services, features or resources we make available on our Site. Users may be asked for, as appropriate, name, email address. Users may, however, visit our Site anonymously. We will collect personal identification information from Users only if they voluntarily submit such information to us. Users can always refuse to supply personally identification information, except that it may prevent them from engaging in certain Site related activities. Passwords are stored as encrypted hashed passwords with automatically generated salts such that the management cannot decrypt User passwords as well.
<br/><br/><br/>

<h2>Non-personal identification information</h2>
<p class="bigtext2">
We may collect non-personal identification information about Users whenever they interact with our Site. Non-personal identification information may include the browser name, the type of computer and technical information about Users means of connection to our Site, such as the operating system and the Internet service providers utilized and other similar information.</p>
<br/><br/>
<h2>Web browser cookies</h2>
<p class="bigtext2">
Our Site may use "cookies" to enhance User experience. User's web browser places cookies on their hard drive for record-keeping purposes. User may choose to set their web browser to refuse cookies, or to alert you when cookies are being sent. If they do so, note that some parts of the Site may not function properly.</p>
<br/><br/>
<h2>How we use collected information</h2>
<p class="bigtext2">

Pollled may collect and use Users personal information for the following purposes:<br/><br/>
- <strong>To improve customer service<br/></strong>
Information you provide helps us respond to your customer service requests and support needs more efficiently.<br/><br/>
- <strong>To personalize user experience<br/></strong>
We may use information in the aggregate to understand how our Users as a group use the services and resources provided on our Site.<br/><br/>
- <strong>To improve our Site<br/></strong>
We may use feedback you provide to improve our products and services.<br/><br/>
- <strong>To share your information with third parties when voluntarily casting a vote on a poll<br/></strong>
We may share or sell information with third parties for marketing or other purposes only when you cast your vote on that particular third party's poll.<br/><br/>
- <strong>To send periodic emails<br/></strong>
We may use the email address to send User information and updates pertaining to their order. It may also be used to respond to their inquiries, questions, and/or other requests. If User decides to opt-in to our mailing list, they will receive emails that may include company news, updates, related product or service information, etc. If at any time the User would like to unsubscribe from receiving future emails, they may do so by contacting us via our Site.</p>
<br/><br/>
<h2>How we protect your information</h2>
<p class="bigtext2">
We adopt appropriate data collection, storage and processing practices and security measures to protect against unauthorized access, alteration, disclosure or destruction of your personal information, username, password, transaction information and data stored on our Site.</p>
<p class="bigtext2">
<strong>Changes to this privacy policy</strong><br/>

Pollled has the discretion to update this privacy policy at any time. When we do, we will revise the updated date at the bottom of this page and send you an email. We encourage Users to frequently check this page for any changes to stay informed about how we are helping to protect the personal information we collect. You acknowledge and agree that it is your responsibility to review this privacy policy periodically and become aware of modifications.<br/><br/>
<strong>Your acceptance of these terms</strong><br/>
By using this Site, you signify your acceptance of this policy. If you do not agree to this policy, please do not use our Site. Your continued use of the Site following the posting of changes to this policy will be deemed your acceptance of those changes.<br/><br/><br/>
<h2>Contacting us</h2>
<p class="bigtext2">
If you have any questions about this Privacy Policy, the practices of this site, or your dealings with this site, please contact us at:<br/><br/>
Pollled.com<br/>
Pollled, Bangalore.<br/>
support@pollled.com<br/>
<br/><br/><br/>
This document was last updated on July 3, 2013<br/><br/><br/></p></div>