config/routes.rb
Poll::Application.routes.draw do
  get "votes/create"

  resources :epolls
  resources :votes

  resources :authentications

  devise_for :users, :path => '', path_names: {sign_in: "login", sign_out: "logout"},
  controllers: {omniauth_callbacks: "authentications", registrations: "registrations"}
  match 'mypolls' => 'epolls#mypolls'
  get "homefront/index"
   get "homefront/about"
  match 'statistics/:id' => 'epolls#statistics', :as => 'statistics'
match 'users/auth/:provider/callback' => 'authentications#create'
match '/auth/:provider/callback' => 'authentications#create'
match 'trending' => 'epolls#trending'
match 'policy' => 'homefront#policy'
match 'the-big-idea' => 'homefront#idea', :as => 'idea'
match 'about' => 'homefront#about'

  root :to => 'homefront#index'

end

app/views/layouts/_analytics.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-41925562-1', 'us.to');
  ga('send', 'pageview');

</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pollled - Your one stop polling destination!</title>

  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
<meta property="og:image" content="http://i42.tinypic.com/2wf74tx.png" />
<%if @epoll%>
<%if @epoll.user%>
<meta name="description" content="Asked by: <%="#{find_user_from_epoll(@epoll)}"%>. Pollled is the ultimate FREE polling solution for the Twitterverse and beyond, packed with statistics, data and reports! ">
<%end%>
<meta name="Title" content="Poll: <%="#{@epoll.question}"%>">
<%end%>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Signika:700,600,400,300' rel='stylesheet' type='text/css'>
</head>
<body>
<%if Rails.env.production? %>
<%= render :partial => 'layouts/analytics' %>
<%end%>
<div id ="navbar">

<div id ="settingsmenu"><div id="drop_icon"></div><br/>
	<div class="openmenu">
	<ul>
		<li><%= link_to "Create Poll", new_epoll_path%></li>
		<%if user_signed_in?%>
		
	<li><%= link_to "My Polls", mypolls_path%></li>
	<%end%>
	
	<li><%= link_to "All Polls", epolls_path%></li>
	<li><%= link_to "Trending Polls", trending_path%></li>
	<%if user_signed_in?%>
	<li><%= link_to "Settings", edit_user_registration_path%></li>
	<li><%= link_to "The Big Idea", idea_path , :class=> 'nccolor'%></li>
	<%end%>
	</ul></div>
	</div>

<%if user_signed_in?%>
<div id ="loginmenu">You are logged in as <%=current_user.email%>.&nbsp;&nbsp;<%= link_to "LOGOUT?", destroy_user_session_path, method: :delete%></div>
<%else%>
<div id="loginmenu"><%=link_to "LOGIN", new_user_session_path%>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<%=link_to "REGISTER", new_user_registration_path%></div>
<%end%>
<a href="http://pollled.com"><div id="logo"></div></a>
</div>
<div class ="container">
<%= yield %>

</div>
<div class="footer">
<div class="footer1">
	&copy;Pollled 2013 |
	<span class="smallesttext"><%=link_to "Privacy Policy", policy_path%></span><br/>
	<br/></div>
<div class="footer2">
<a href="https://www.facebook.com/pages/Pollled/677102765641499"><div class="pfb"></div></a>
<a href="http://sizr.net"><div class="psi"></div></a>
<a href="https://twitter.com/Pollled"><div class="ptw"></div></a>
</div>
</div>
</body>
</html>